Repository XPEHO/UDSP59, pull requests merged in 2023-11, with the labels that each got.

#32 chore(release): setup release build
  .gitignore
  android/app/build.gradle
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
Labels: chore :construction_worker_man:

#33 chore(workflow): create upload bundle workflow
  .github/workflows/upload_appbundle_internal.yaml
Labels: chore :construction_worker_man:

#41 fix(homepage): Add a padding and a privacy policy link on homepage
  assets/translations/fr.json
  lib/views/home_page.dart
  test/widget_test.dart
Labels: bug :bug:

#43 feat(tips): make simplification proposal
  analysis_options.yaml
  lib/features/tips_card.dart
  lib/features/tips_card_switcher.dart
  lib/main.dart
  lib/state/notifiers/tips_notifiers.dart
  lib/state/providers/tips_providers.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: enhancement :rocket:

#44 test(golden_tests): Add tests golden
  .github/workflows/sonar.yaml
  .github/workflows/test_&_build.yaml
  lib/features/module_accordion_element.dart
  lib/features/url_linked_icon.dart
  lib/views/about_page.dart
  pubspec.lock
  pubspec.yaml
  test/flutter_test_config.dart
  test/golden_test.dart
  test/goldens/module_accordion_element_grid.png
  test/goldens/modules_carousel_element.png
  test/goldens/page_header.png
  test/goldens/tips_card_switcher.png
  test/goldens/title_header.png
  test/goldens/url_linked_icon.png
Labels: other

#48 fix(tips_card_width): provide width change by fixing the width
  lib/features/tips_card_switcher.dart
Labels: bug :bug:

#47 fix(breakpoints): convert arbitrary values in breakpoints
  lib/features/modules_carousel.dart
  lib/features/title_header.dart
  lib/styles/form_factor.dart
Labels: bug :bug:

#54 fix(byxpeho): Add the productor of the app
  assets/translations/fr.json
  lib/views/home_page.dart
  pubspec.lock
Labels: bug :bug:

#55 chore(bump): bump to 1.2.0
  pubspec.lock
  pubspec.yaml
Labels: chore :construction_worker_man:
